function weights = cubicInterpolationWeights(t)
    % Cubic interpolation weights
    a = -0.5;
    weights = [(a*(t+2)^3 - 5*a*(t+2)^2 + 8*a*(t+2) - 4*a), ...
               (a*t^3 - 5*a*t^2 + 4*a*t + 2*a), ...
               (-a*(t-2)^3 + 5*a*(t-2)^2 + 8*a*(t-2) + 4*a), ...
               (-a*(t-3)^3 + 5*a*(t-3)^2 - 8*a*(t-3) - 4*a)];
end
